### ISSUE TITLE
  Неправильное имя файла .gitognore

### ISSUE THREAD

**Issue by ErDmKo** [annadarina/test_task#1]
@annadarina 
Чтобы это работало нужно назвать его .gitignore

**Comment by annadarina** [comment]
точно, спасибо, что заметил)

**Comment by ErDmKo** [comment]
Только теперь нужно наверно удалить их из индекса /node_modules/ и /test_html_js/ 
Вроде должно помочь что типа:
`git rm -r --cached ./node_modules/ ./test_html_js/ `
